module.exports = {
  flutter: [
    'flutter/what-is-flutter',
    {
      type: 'category',
      label: 'Dart',
      collapsed: false, // 펼쳐진 상태로 시작
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated', dirName: 'flutter/grammar',
        }
      ]
    },
    {
      type: 'category',
      label: 'Theory',
      collapsed: true, // 접힌 상태로 시작
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated', dirName: 'flutter/theory',
        }
      ]
    },
    {
      type: 'category',
      label: 'Widget',
      collapsed: true, // 접힌 상태로 시작
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated', dirName: 'flutter/widget',
        },
        {
          type: 'category',
          label: 'Scrollalbe Widget',
          link: {
            type: 'doc',
            id: 'exceptions/scrollable-widget/index'
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'exceptions/scrollable-widget/scrollable-widget'
            }
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Packeages',
      collapsed: true, // 접힌 상태로 시작
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated', dirName: 'flutter/packages',
        },
      ]
    },
  ],

  // tutorial sidebar
  tutorial: [
    'intro',
    {
      type: 'category',
      label: 'Tutorial-Basics',
      collapsed: false,
      link: { // category 클릭하면 해당하는 category의 모든 문서를 보여줌
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial/tutorial-basics',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorial-Extras',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial/tutorial-extras',
        },

      ],
    }
  ],
};
